      version: "3.7"
      services:
        mysql:
          image: mysql:5.7
          container_name: mysql
          ports:
            - "3306:3306"
          environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: stationSki
          volumes:
            - mysql_data:/var/lib/mysql
            - mysql_config:/etc/mysql/conf.d
          networks:
            - app-network
        spring-app:
          image: "sarrachaouch/gestion-station-ski-1.0"
          ports:
            - "8089:8089"
          environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true&useSSL=false&max_allowed_packet=15728640
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=
          depends_on:
            - mysql
          networks:
            - app-network


      volumes:
        mysql_data:
        mysql_config:

      networks:
        app-network:
          driver: bridge
